title: Shoutem Developers
email: -
description: Supercharge your React Native development with Shoutem
twitter_username: -
github_username:  myark
tracking_id: UA-807293-5

sass:
  style: compressed

# Build settings
markdown: kramdown

kramdown: 
  syntax_highlighter_opts:
    disable : true

url: "https://myark.github.io/shoutem-cn"
exclude: ['api-src/']
